export declare const CARD_RARITIES: readonly ["Common", "Uncommon", "Rare", "Epic", "Showcase", "Alternate Art", "Overnumbered"];
export type CardRarity = (typeof CARD_RARITIES)[number];
export declare const CARD_TYPES: readonly ["Unit", "Champion Unit", "Spell", "Legend", "Signature Unit", "Signature Spell", "Gear", "Signature Gear"];
export type CardType = (typeof CARD_TYPES)[number];
export declare const CARD_DOMAINS: readonly ["Fury", "Calm", "Mind", "Body", "Chaos", "Order"];
export type CardDomain = (typeof CARD_DOMAINS)[number];
export declare const CARD_CONDITIONS: readonly ["near_mint", "lightly_played", "moderately_played", "heavily_played", "damaged"];
export type CardCondition = (typeof CARD_CONDITIONS)[number];
export declare const CARD_VARIANTS: readonly ["normal", "alt_art", "overnumbered", "signature"];
export type CardVariant = (typeof CARD_VARIANTS)[number];
export declare const WISHLIST_TYPES: readonly ["want", "trade"];
export type WishlistType = (typeof WISHLIST_TYPES)[number];
export declare const FOIL_VARIANTS: ReadonlySet<CardVariant>;
export declare function isFoilVariant(variant: string): boolean;
export declare const DECK_ZONES: readonly ["main", "rune", "champion", "sideboard"];
export type DeckZone = (typeof DECK_ZONES)[number];
export declare const MAX_COPIES_PER_CARD = 3;
export declare const MAX_SIGNATURE_COPIES = 1;
export declare const MAIN_DECK_SIZE = 40;
export declare const RUNE_DECK_SIZE = 12;
export declare const CHAMPION_COUNT = 1;
export declare const SIDEBOARD_SIZE = 8;
export declare const SIGNATURE_TYPES: readonly ["Signature Unit", "Signature Spell", "Signature Gear"];
export type SignatureType = (typeof SIGNATURE_TYPES)[number];
export declare function getZoneForCardType(cardType: string | null): DeckZone;
