export enum Region {
  NOXUS = 'NOXUS',
  THE_VOID = 'THE_VOID',
  DEMACIA = 'DEMACIA',
  IONIA = 'IONIA',
  PILTOVER = 'PILTOVER',
  ZAUN = 'ZAUN',
  FRELJORD = 'FRELJORD',
  SHURIMA = 'SHURIMA',
  BILGEWATER = 'BILGEWATER',
  SHADOW_ISLES = 'SHADOW_ISLES',
  TARGON = 'TARGON',
  BANDLE_CITY = 'BANDLE_CITY',
}
